apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomcats
  namespace: default
  labels:
    app: randomcats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: randomcats
  template:
    metadata:
      labels:
        app: randomcats
    spec:
      containers:
        - name: randomcats
          image: randomcats:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: randomcats-service
  namespace: default
spec:
  selector:
    app: randomcats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP      