apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomcats-ingress
  namespace: default
  annotations:
    # Eger NGINX Ingress Controller kullaniyorsaniz bu satir gereklidir:
    kubernetes.io/ingress.class: "nginx"
    # Dosya yukleme limiti vb. ayarlar icin ornek annotation:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: 34.123.31.225.nip.io  # domain ismi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: randomcats-service # servis ismi
            port:
              number: 80 # Serviste tanimlanan port