apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomcats-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: 34.123.31.225.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: randomcats-service
            port:
              number: 80